#!/usr/bin/env bash
# This script loops from 1 to 20 displaying
# "4" and then "bad luck from China" for the 4th iteration
# "9" and then "bad luck from Japan" for the 4th iteration
# "17" and then "bad luck from Italy" for the 4th iteration

i=1
while [ $i -le 20 ]
do
    echo $i
    case $i in
        4) echo bad luck from China ;;
        9) echo bad luck from Japan ;;
        17) echo bad luck from Italy ;;
    esac
    ((i++))
done
